# install_helm.yml
---
- name: Instalar Helm en el nodo controlador (localhost servidor fisico )
  hosts: localhost
  become: true
  vars:
    helm_version: "v3.14.0"
  tasks:

    - name: ğŸ“ Crear directorio temporal
      file:
        path: /tmp/helm_install
        state: directory

    - name: ğŸ“¥ Descargar Helm {{ helm_version }}
      get_url:
        url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
        dest: "/tmp/helm_install/helm.tar.gz"

    - name: ğŸ“¦ Extraer Helm
      unarchive:
        src: "/tmp/helm_install/helm.tar.gz"
        dest: "/tmp/helm_install/"
        remote_src: yes

    - name: ğŸ—‚ Verificar que el binario helm existe
      stat:
        path: /tmp/helm_install/linux-amd64/helm
      register: helm_bin_check

    - name: âœ… Mover binario de Helm a /usr/local/bin
      copy:
        src: /tmp/helm_install/linux-amd64/helm
        dest: /usr/local/bin/helm
        mode: '0755'
        remote_src: true
      when: helm_bin_check.stat.exists

    - name: ğŸ§ª Verificar versiÃ³n de Helm instalada
      command: /usr/local/bin/helm version
      register: helm_output

    - name: ğŸ“Š Mostrar salida de Helm
      debug:
        msg: "{{ helm_output.stdout }}"

    - name: ğŸ§¹ Limpiar archivos temporales
      file:
        path: /tmp/helm_install
        state: absent